apiVersion: v2
appVersion: "1.0"
description: Helm chart for Kubernetes => deploy a FastAPI
maintainers:
  - email: wimpie@howest.be
    name: wimpie
name: fastapi-oei
sources:
  - https://github.com/w-vanhoey/helm-prepex
version: 1.3.0