replicaCount: 1

image:
  repository: ghcr.io/w-vanhoey/fastapi-prepex  # Package ref / You can keep this on my image, because of the Pull Secrets (public)
  tag: v1.4 #tag: latest ##  tag: v1.0                   # INDENTATION IS CRITICAL # USE YAML VALIDATOR IN CASE OF TROUBLE

nameOverride: "hoey-fastapi-prepex3"
fullNameOverride: "hoey-fastapi-prepex3-de"

serviceAccount:
    create: true
    name: helm-service-account ## This is a name you can choose yourself

## Keep these empty for the first try.
##imagePullSecrets: [] # Here you can fill in your own Pull Secret if you do want to work with your own repository
##nodeSelector: {} # Fill in the right Node Selector here.

## Private repository 
##------------------------------------
nodeSelector:
   kubernetes.io/hostname: "vanhoey-wim"    # Name of the Project (or Namespace)
   # or
   # nodeName: "vanhoey-wim"
   #kubernetes.io/os: "linux"
imagePullSecrets:
   - name: "ghcr-vanhoey-wim-ah"             # Name of the secret