replicaCount: 2

image:
  repository: ghcr.io/w-vanhoey/2021-2022-mlopsathome-fastapi-prepEx # You can keep this on my image, because of the Pull Secrets
  tag: v1.0.0

nameOverride: "hoey-fastapi-prepex"
fullNameOverride: "hoey-fastapi-prepex-demo"

serviceAccount:
    create: true
    name: helm-service-account ## This is a name you can choose yourself

## Keep these empty for the first try.
imagePullSecrets: [] # Here you can fill in your own Pull Secret if you do want to work with your own repository
nodeSelector: {} # Fill in the right Node Selector here.