# The Kubernetes service Accounts that will be created

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "example.serviceAccountName" . }}
  labels:
{{ include "example.labels" . | indent 4 }}
{{- end -}}